apiVersion: v1
kind: Service
metadata:
  name: yt-summarizer-api-service
spec:
  selector:
    app: yt-summarizer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
